### PR TITLE
Explicit Principal code sample is wrong (#33)

### LINKED ISSUE #33: Explicit Principal code sample is wrong
The sample says:
```
name = gssapi.Name("user@REALM", gssapi.NameType.hostbased_service)
creds = gssapi.Credentials(name=name, usage="initiate")
```
but the provided principal is not a hostbased service eligible for initiate.

### PR DESCRIPTION
**Pull request by michael-o**
This closes #33

### CODE REVIEW

**Comment by michael-o** [comment]
@frozencemetery Please have a look.

**Review by simo5 — APPROVED** [review]
Looks good to me

**Comment by simo5** [comment]
@michael-o, you need to rewrite your commit comment to add your signature, DCO required in this repo.

**Comment by michael-o** [comment]
@simo5 Done. Is that sufficient?

**Comment by simo5** [comment]
The bot is happy :-)

**Review by frozencemetery — APPROVED** [review]

**Pull request merged**
