### PR TITLE
README: fix opportunistic_auth example

### PR DESCRIPTION
**Pull request by ktdreyer**
The `HTTPSPNEGOAuth` constructor uses a keyword argument named `opportunistic_auth`, not `opportunistic_authentication`. Fix the example in the README to reflect this.

### CODE REVIEW

**Comment by ktdreyer** [comment]
(Would you mind tagging and pushing a new version to PyPI? I was following the README on PyPI when I hit this bug.)

**Comment by frozencemetery** [comment]
(I'm looking at merging another fix before cutting a release, but should do that shortly.)

**Comment by frozencemetery** [comment]
A new release has been cut.  Thanks for your interest!

**Comment by ktdreyer** [comment]
Thank you!

**Pull request merged**
